### PR TITLE
fix: Manage horizontal margin when apply in tileStyle props.

### PR DESCRIPTION
**Pull request by Krunal-K-SimformSolutions**

### CODE REVIEW

**Comment by Karthik-B-06** [comment]
@Krunal-K-SimformSolutions With there many changes in the file, I am not able to understand what exactly are we trying to fix?

An issue first followed by a PR would have helped :)

**Comment by Krunal-K-SimformSolutions** [comment]
@Karthik-B-06: Here I am added dynamic margin because you have applied static margin 4 but when a user provides margin on 'tileStyle' attribute that causes the issue of active segment indicator margin.

Check line number 35, 36 in 
```
const marginHorizontal = (props.tileStyle.marginHorizontal || 2) * 2;
const translateValue = (width - marginHorizontal) / props?.tabs?.length;
```
And 84 in 
```
width: (width - marginHorizontal) / props?.tabs?.length
```
Other changes for eslint and prettier format change.

**Comment by Karthik-B-06** [comment]
@Krunal-K-SimformSolutions Can you change the PR base branch to `development`, that way I can fix those eslint/prettier issues and go ahead and merge this fix.

**Comment by Karthik-B-06** [comment]
@Krunal-K-SimformSolutions 
Adding a dynamic margin other than the static value breaks the style. 
```
      <SegmentedControl
        tabs={["Label", "Label"]}
        onChange={() => {}}
        paddingVertical={6}
        containerStyle={{
          marginVertical: 20,
          borderRadius: 15,
        }}
        tileStyle={{
          borderRadius: 15,
          marginHorizontal: 16
        }}
        currentIndex={tabIndex}
        onChange={handleTabsChange}
        theme={theme}
      />
```


simulator_screenshot_375791EF-0536-4925-A3F7-A083866408E3

This is the result after your changes are in effect.

**Pull request merged**
